# This is the configuration file for the main plates of data (prior to re-imaging).
channels:
    Brightfield high: OrigBrightfield
    Alexa 488: OrigER
    Alexa 568: OrigAGP
    Alexa 647: OrigMito
    HOECHST 33342: OrigDNA
    Alexa 488 Long (CP): OrigRNA

metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    ChannelID: ChannelID
    PositionX: PositionX
    PositionY: PositionY
    PositionZ: PositionZ
    AbsPositionZ: AbsPositionZ
