#!/bin/bash
# Run the load_data_csv step for every plate in Rounds 2-4 (Round 1 already done).
# Generated 2026-08-28 -- run these one at a time and check each one's output before moving on;
# relocate_load_data_csv.py refuses to write if a row's path doesn't resolve.

set -e

echo "=== Round 2 ==="
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round2.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_2_data/BR00145438_concatenated.csv" --batch-name Round2_Plate3 --plate-name BR00145438 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round2_Plate3/BR00145438/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round2.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_2_data/BR00145439_concatenated.csv" --batch-name Round2_Plate3 --plate-name BR00145439 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round2_Plate3/BR00145439/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round2.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_2_data/BR00145440_concatenated.csv" --batch-name Round2_Plate3 --plate-name BR00145440 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round2_Plate3/BR00145440/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round2.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_2_data/BR00145816_concatenated.csv" --batch-name Round2_Plate4 --plate-name BR00145816 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round2_Plate4/BR00145816/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round2.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_2_data/BR00145817_concatenated.csv" --batch-name Round2_Plate4 --plate-name BR00145817 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round2_Plate4/BR00145817/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round2.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_2_data/BR00145818_concatenated.csv" --batch-name Round2_Plate4 --plate-name BR00145818 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round2_Plate4/BR00145818/load_data.csv

echo "=== Round 3 ==="
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00146998_concatenated.csv" --batch-name Round3_Plate5 --plate-name BR00146998 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate5/BR00146998/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00146999_concatenated.csv" --batch-name Round3_Plate5 --plate-name BR00146999 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate5/BR00146999/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147000_concatenated.csv" --batch-name Round3_Plate5 --plate-name BR00147000 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate5/BR00147000/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147001_concatenated.csv" --batch-name Round3_Plate6 --plate-name BR00147001 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate6/BR00147001/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147002_concatenated.csv" --batch-name Round3_Plate6 --plate-name BR00147002 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate6/BR00147002/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147003_concatenated.csv" --batch-name Round3_Plate6 --plate-name BR00147003 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate6/BR00147003/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147261_concatenated.csv" --batch-name Round3_Plate8 --plate-name BR00147261 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate8/BR00147261/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147262_concatenated.csv" --batch-name Round3_Plate8 --plate-name BR00147262 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate8/BR00147262/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147263_concatenated.csv" --batch-name Round3_Plate8 --plate-name BR00147263 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate8/BR00147263/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147495_concatenated.csv" --batch-name Round3_Plate7 --plate-name BR00147495 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate7/BR00147495/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147496_concatenated.csv" --batch-name Round3_Plate7 --plate-name BR00147496 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate7/BR00147496/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round3.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_3_data/BR00147497_concatenated.csv" --batch-name Round3_Plate7 --plate-name BR00147497 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round3_Plate7/BR00147497/load_data.csv

echo "=== Round 4 ==="
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00147482_concatenated.csv" --batch-name Round4_Plate9 --plate-name BR00147482 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate9/BR00147482/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00147483_concatenated.csv" --batch-name Round4_Plate9 --plate-name BR00147483 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate9/BR00147483/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00147484_concatenated.csv" --batch-name Round4_Plate9 --plate-name BR00147484 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate9/BR00147484/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148739_concatenated.csv" --batch-name Round4_Plate11 --plate-name BR00148739 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate11/BR00148739/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148740_concatenated.csv" --batch-name Round4_Plate11 --plate-name BR00148740 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate11/BR00148740/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148741_concatenated.csv" --batch-name Round4_Plate11 --plate-name BR00148741 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate11/BR00148741/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148744_concatenated.csv" --batch-name Round4_Plate10 --plate-name BR00148744 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate10/BR00148744/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148745_concatenated.csv" --batch-name Round4_Plate10 --plate-name BR00148745 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate10/BR00148745/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148746_concatenated.csv" --batch-name Round4_Plate10 --plate-name BR00148746 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate10/BR00148746/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148751_concatenated.csv" --batch-name Round4_Plate12 --plate-name BR00148751 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate12/BR00148751/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148752_concatenated.csv" --batch-name Round4_Plate12 --plate-name BR00148752 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate12/BR00148752/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148753_concatenated.csv" --batch-name Round4_Plate12 --plate-name BR00148753 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate12/BR00148753/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148800_concatenated.csv" --batch-name Round4_Plate13 --plate-name BR00148800 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate13/BR00148800/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148801_concatenated.csv" --batch-name Round4_Plate13 --plate-name BR00148801 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate13/BR00148801/load_data.csv
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/relocate_load_data_csv.py --manifest /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/assets/manifest_round4.yaml --csv "/media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/1.illumination_correction/loaddata_csvs/Round_4_data/BR00148802_concatenated.csv" --batch-name Round4_Plate13 --plate-name BR00148802 --target /media/18tbdrive/cpg_pilot_transfer --out /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma/alexslemonade/workspace/load_data_csv/Round4_Plate13/BR00148802/load_data.csv

echo "=== Validating ==="
python3 /media/18tbdrive/1.Github_Repositories/pediatric_cancer_pilot_atlas_profiling/cpg-pilot-data-organizer/scripts/validate_structure.py /media/18tbdrive/cpg_pilot_transfer/cpg0041-pccma
